name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ./ngrok

      - name: Authenticate ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Set ngrok configuration
        run: |
          New-Item -ItemType Directory -Path "$env:USERPROFILE\.ngrok2" -Force
          @"
          region: eu
          "@" | Out-File -FilePath "$env:USERPROFILE\.ngrok2\ngrok.yml" -Encoding utf8
          
      - name: Enable Terminal Services (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          # Создаём пользователя runneradmin с безопасным паролем из секретов
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "$Env:RUNNER_ADMIN_PASSWORD" -Force)
        env:
          RUNNER_ADMIN_PASSWORD: ${{ secrets.RUNNER_ADMIN_PASSWORD }}

      - name: Create ngrok TCP Tunnel
        run: .\ngrok\ngrok.exe tcp 3389 --config "$env:USERPROFILE\.ngrok2\ngrok.yml"
