name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ./ngrok

      - name: Authenticate ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create ngrok Config File
        run: |
          $configContent = @"
          authtoken: $Env:NGROK_AUTH_TOKEN
          tunnels:
            my_tcp_tunnel:
              proto: tcp
              addr: 3389
              region: eu
          "@
          # Создаём папку для конфигурации, если не существует
          New-Item -ItemType Directory -Path .\ngrok -Force
          # Сохраняем конфигурационный файл
          Set-Content -Path .\ngrok\ngrok.yml -Value $configContent
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Terminal Services (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          # Создаём пользователя runneradmin с безопасным паролем из секретов
          $securePassword = ConvertTo-SecureString -AsPlainText $Env:RUNNER_ADMIN_PASSWORD -Force
          if (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue) {
            Set-LocalUser -Name "runneradmin" -Password $securePassword
          } else {
            New-LocalUser -Name "runneradmin" -Password $securePassword -FullName "Runner Admin" -Description "User for RDP access"
            Add-LocalGroupMember -Group "Administrators" -Member "runneradmin"
          }
        env:
          RUNNER_ADMIN_PASSWORD: ${{ secrets.RUNNER_ADMIN_PASSWORD }}

      - name: Start ngrok TCP Tunnel
        run: .\ngrok\ngrok.exe start my_tcp_tunnel --config .\ngrok\ngrok.yml
