name: RDP Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok

      - name: Authenticate ngrok
        run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Create RDP User
        run: |
          $Password = ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force
          New-LocalUser -Name "runneradmin" -Password $Password -FullName "RDP User" -Description "User for RDP access" -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "runneradmin"

      - name: Start ngrok tunnel
        run: .\ngrok\ngrok.exe tcp 3389 --region eu
        # Замените 'eu' на желаемый регион: us, eu, ap, au, etc.

      - name: Output ngrok URL
        run: |
          $ngrokInfo = .\ngrok\ngrok.exe tcp 3389 --region eu --log=stdout
          Write-Output "RDP доступен по адресу: $($ngrokInfo | Select-String 'tcp://').Line"
